[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.3
    adafruit/Adafruit BusIO@^1.17.0
